

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5433}/paymentdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
#    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect



    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

